[versions]
auto-service = "1.1.1"
detekt = "1.23.8"
kotlin = "2.2.21"
junit-platform = "6.0.1"

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "5.7.1" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version = "2.5.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-power-assert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
plugin-publish = { id = "com.gradle.plugin-publish", version = "2.0.0" }

[libraries]
google-autoservice = { module = "com.google.auto.service:auto-service", version.ref = "auto-service" }
google-autoservice-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-service" }
hamcrest = { module = "org.hamcrest:hamcrest", version = "3.0"}
junit4 = { module = "junit:junit", version = "4.13.2" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-engine", version.ref = "junit-platform" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
junit-platform-testkit = { module = "org.junit.platform:junit-platform-testkit", version.ref = "junit-platform" }
kotlin-compile-testing = { module = "dev.zacsweers.kctfork:core", version = "0.11.0" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
