name: Publish

on:
  workflow_dispatch:
    inputs:
      component:
        description: 'Component to release'
        default: 'all'
        type: choice
        options:
          - all
          - spockk-docs
          - spockk-core
          - spockk-compiler-plugin
          - spockk-gradle-plugin
          - spockk-intellij-plugin

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Gradle
        uses: ./.github/actions/setup-gradle
      - name: Build artifacts
        run: ./gradlew build
      - name: Publish core module
        if: ${{ github.event.inputs.component == 'spockk-core' || github.event.inputs.component == 'all' }}
        uses: ./.github/actions/publish-maven-central
        with:
          module: "spockk-core"
          mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signingInMemoryKeyId: ${{ secrets.PGP_SIGNING_KEY_ID }}
          signingInMemoryKey: ${{ secrets.PGP_SIGNING_KEY }}
          signingInMemoryKeyPassphrase: ${{ secrets.PGP_SIGNING_KEY_PASSPHRASE }}
      - name: Publish Kotlin compiler plugin module
        if: ${{ github.event.inputs.component == 'spockk-compiler-plugin' || github.event.inputs.component == 'all' }}
        uses: ./.github/actions/publish-maven-central
        with:
          module: "spockk-compiler-plugin"
          mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signingInMemoryKeyId: ${{ secrets.PGP_SIGNING_KEY_ID }}
          signingInMemoryKey: ${{ secrets.PGP_SIGNING_KEY }}
          signingInMemoryKeyPassphrase: ${{ secrets.PGP_SIGNING_KEY_PASSPHRASE }}
      - name: Publish documentation
        if: ${{ github.event.inputs.component == 'spockk-docs' || github.event.inputs.component == 'all' }}
        uses: ./.github/actions/publish-docs
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
